# Generated by Django 2.2.2 on 2019-08-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to='myFiles'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_post',
            field=models.ImageField(null=True, upload_to='post_images'),
        ),
    ]
